# Data Source Configuration
data_source:
  provider: "yfinance"
  period: "5d"  # 1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max
  interval: "1d"  # 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo

# Stock Tickers Configuration
tickers:
  us_stocks:
    - TSLA
    - META
    - NVDA
    - PLTR
    - INTC
  
  indian_stocks:
    - TATAMOTORS.NS
    - TCS.NS
    - HDFCBANK.NS
    - INFY.NS
    - ICICIBANK.NS

# GCS Storage Configuration
storage:
  provider: "gcs"
  raw_data_path: "raw"
  file_format: "csv"
  include_timestamp: true
  include_index: true

# Pipeline Configuration
pipeline:
  rate_limit_delay: 10  # seconds between API calls
  retry_attempts: 3
  retry_delay: 5  # seconds
  enable_validation: true
  enable_logging: true